import React, { useState, useEffect } from 'react'
import { Card, FormField, Loader } from '../components';



const Home = () => {
  const [loading, setLoading] = useState(false);
  const [AllPosts, setAllPosts] = useState(null);
  const [searchText, setsearchText] = useState('');

  return (
    <section className='max-w-7xl mx-auto'>
      <div className=' text-[#222328] text-[32px]'>
        <h1 className='font-extrabold'>The Community Showcase</h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
          Browse through a collection of imaginative and visually stunning images generated by STACKSON.AI
        </p>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing result <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
          </>
        )}
      </div>

    </section>
  )
}

export default Home
